### ISSUE TITLE
ANy plans to have a official release?

### ISSUE THREAD

**Issue by uhlhosting** [mikroskeem/hackermatternews#1]
Hi 

ANy plans to release this after:
https://developers.mattermost.com/extend/plugins/

**Comment by mikroskeem** [comment]
No not really, I find that webhook solution works pretty fine and is simple enough for this task.

Plugin for would make more sense if users could link their accounts to HN, add comments etc. but I'm not interested in implementing this myself.

However, PR-s are always welcome :)

**Comment by mikroskeem** [comment]
Honestly not sure if I misunderstood your question or not... By "official release" you mean a release on GitHub? Or still "please can you turn this into a Mattermost plugin"?
